apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981315520969:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XLLGN96UKUTH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::981315520969:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-11T12:55:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1613"
  uid: 33d221c4-6ad5-40de-a152-4825a564dcc5
