apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::981315520969:user/myAdmin
      username: myAdmin
      groups:
      - system:masters
      - system:nodes
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981315520969:role/eksctl-simple-jwt-api-2-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::981315520969:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-apaplied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: \u003cARN of instance role (not instance profile)\u003e\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-10-07T14:19:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "25945"
  uid: 288051bc-221b-4ac4-8354-559e56e2c7f4
